[env:Flushable]
extends = nrf52840_base
board = promicro-nrf52840
board_level = extra
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/diy/nrf52_promicro_diy_tcxo
  -D PRIVATE_HW
  -D USE_SSD1306
  -D INPUTDRIVER_ENCODER_TYPE=2
  -D INPUTDRIVER_ENCODER_UP=34
  -D INPUTDRIVER_ENCODER_DOWN=33
  -D INPUTDRIVER_ENCODER_BTN=35
  -D UPDOWN_LONG_PRESS_REPEAT_INTERVAL=150
  -D ALLOW_INPUT_SOURCE=_all
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/diy/nrf52_promicro_diy_tcxo>
lib_deps = 
  ${nrf52840_base.lib_deps}
debug_tool = jlink